// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  HorizontalSpace = 1,
  LineComment = 2,
  Document = 3,
  LineEnd = 4,
  StatementList = 5,
  Statement = 6,
  TreeStatement = 7,
  Identifier = 8,
  String = 9,
  NodeStatement = 10,
  NodeKeyword = 11,
  AttributeStatement = 12,
  AttributeValue = 13,
  LinkStatement = 14,
  ConnectionStatement = 15
